export const LANDING_PAGE_URL="/"
export const APP_USER_URL="/appuser"
export const FINACE_DETAILS_URLS="/finacedetails"
export const FIND_VEHICLE_URLS="/findvehicle"
export const DETAILS_VIEW_URLS="/detailsView"
export const UPLOAD_DETAILS_URLS="/upload_details"
export const PROFILE_PAGES_URLS="/profile_page"